name: validate
on:
  pull_request_target:
    types:
      - closed
      - labeled
    branches:
      - main
      - 'release/*.*.x'
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: print event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT"
    