name: validate
on:
  pull_request:

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: print event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT"
    